mapzen/eraser-map

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/view_route_mode.xml
app/src/main/res/values/dimens.xml
app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java

- Fixes transition between route preview and route mode
- Adds route footer in route mode

adds footer and fixes view transitions

---

app/src/main/AndroidManifest.xml

- Based on the documentation we need to specify opengles version in the manifest else its defined to pick 1.0 as the
default!
http://developer.android.com/guide/topics/manifest/uses-feature-element.html#glEsVersion

Specify opengl es version in androidmanifest

---

app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/java/com/mapzen/erasermap/CommonModule.java
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java
app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt

Prevents replay of completed instructions when rotating the device during routing.
* Make RouteEngine a singleton
* Extracts RoutePresenter
* Do not reset RouteEngine if already routing
* Verify icon is ImageView to prevent type cast error

Maintain route state on rotation

---

app/src/main/assets/scene.yaml

- fixes "shader compilation issue" and `validate_vertex_attribute_state: No vertex attrib is enabled in the draw!` log messages
- seems to be caused by trying to use a uniform in the scene yaml, which was removed in the recent changes made
to tangram

Update scene yaml

---

app/build.gradle
app/src/main/java/com/mapzen/erasermap/EraserMapApplication.java
app/src/test/java/com/mapzen/erasermap/PrivateMapsTestRunner.java
app/src/test/java/com/mapzen/erasermap/shadows/ShadowMultiDex.java

Fixes immediate crash at launch on pre-Lollipop devices. Dagger was unable to resolve generated classes built into additional dex files.

Adds multidex support library

---

app/src/main/kotlin/com/mapzen/erasermap/model/TileHttpHandler.kt

Unfortunately because of how Kotlin handles Java static fields we are unable to use [`Build.VERSION_CODES.KITKAT`](https://developer.android.com/reference/android/os/Build.VERSION_CODES.html#KITKAT). Kotlin resolves this value at runtime instead of compile time which produces a [`NoSuchFieldError`](https://developer.android.com/reference/java/lang/NoSuchFieldError.html) and crashes the application when running on OS versions prior to KitKat.

Init tile cache on KitKat and newer only!

---

app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

Prevents registering the MainPresenter twice with Otto by removing property and initializing via constructor injection.

Prevent event bus crash on startup

---

app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouteManager.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RoutePreviewView.kt
app/src/main/kotlin/com/mapzen/erasermap/view/SearchResultsAdapter.kt
app/src/test/java/com/mapzen/erasermap/dummy/TestHelper.java
app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt
app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java
app/src/test/java/com/mapzen/erasermap/view/RoutePreviewViewTest.java
app/src/test/java/com/mapzen/erasermap/view/SearchResultsAdapterTest.java

Tapping on an autocomplete item in recent searches takes user directly to to the same result. Denotes saved auto-complete items with a pin rather than timer icon.
* Persist payload for auto-complete items
* Reconstruct features for saved items in recent list
* Feature and SimpleFeature API updates
Closes #87

Adds auto-complete saved searches

---

app/src/main/kotlin/com/mapzen/erasermap/view/SearchResultsListActivity.kt
app/src/test/java/com/mapzen/erasermap/view/SearchResultsListActivityTest.java

Implements custom `ArrayAdapter` that uses `SimpleFeature.label()` method for display text.
Closes #145

Fix display text when viewing all search result

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt

Prevents situation where you would be unable to clear search results and back button instead would exit the application.
* Remove action view expand listener since search is now always expanded
* Trigger "expand" when search view gains focus and "collapse" on back pressed
* Remove hacky search view width calculations
* Always show overflow or view all action to preserve correct spacing
* Clear query text on exit search
Closes #132

Improve search UI back stack management

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteViewController.kt
app/src/test/java/com/mapzen/erasermap/PrivateMapsTestRunner.java
app/src/test/java/com/mapzen/erasermap/shadows/ShadowTangram.java
app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/view/TestRouteController.kt
config/checkstyle/checkstyle-suppressions.xml

Clears both route navigation and find me location markers on device rotation. Replaces markers when map is re-created. Adds `ShadowTangram` class to enable testing.
Closes #108

Clear location markers on rotation

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt
app/src/test/java/com/mapzen/erasermap/dummy/TestHelper.java
app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt

`MainActivity` now passes all long press events to the `MainPresenter` which decides whether or not to proceed with reverse geocoding based on current view state.
Closes #148

Prevent long press to reverse geolocate in routing mode

---

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt

- also fixes route icon flickering
- tested with a driving test and back... all worked.

Updated to use new client data API

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt

* Track user swipe on view pager vs. programatic changes
* Do not show resume button unless map is moved minimum distance by user
* Do not reset map position to current instruction while user is panning the map
Closes #74

Refinements for interacting with map in routing mode

---

app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/kotlin/com/mapzen/erasermap/model/RouterFactory.kt
app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouteManager.kt
app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouterFactory.kt
app/src/test/kotlin/com/mapzen/erasermap/model/TestRouteManager.kt
app/src/test/kotlin/com/mapzen/erasermap/model/TestRouter.kt
app/src/test/kotlin/com/mapzen/erasermap/model/TestRouterFactory.kt
app/src/test/kotlin/com/mapzen/erasermap/model/ValhallaRouteManagerTest.kt

* Only set name param if a POI name is available.
* Do not set name parameter if the destination is a street address.
* Uses Pelias `layer` field to distinguish address only features.
Closes #137

Do not set name in route request for address features

---

app/src/main/kotlin/com/mapzen/erasermap/model/AndroidAppSettings.kt
app/src/main/kotlin/com/mapzen/erasermap/model/AppSettings.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt
app/src/main/res/values/settings.xml
app/src/main/res/xml/preferences.xml
app/src/test/java/com/mapzen/erasermap/shadows/ShadowTangram.java
app/src/test/kotlin/com/mapzen/erasermap/model/AndroidAppSettingsTest.kt
app/src/test/kotlin/com/mapzen/erasermap/model/TestAppSettings.kt
config/checkstyle/checkstyle-suppressions.xml

This is mostly to aid in style evaluation and debugging. With tile debug info enabled, the boundaries and coordinates (x, y, zoom) of each tile is made visible. With label debug info enabled, anchor points and bounding boxes for each label are made visible. 
I considered making this a single toggle but the label debug drawing is quite slow and usually not needed. Remaining nitpicks:
- ~~Settings aren't applied until the settings menu is opened (i.e. until a `SettingsFragment` is created); not sure how to fix this most simply.~~ (Thanks Chuck!)
- Tile debug info is only applied to new tiles, not already-rendered tiles. This is really a thing that's best fixed within Tangram-ES, so I'll take care of that there. 
Closes #167

Add settings to enable debug drawing for tiles and labels

---

app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt

1. First the map position is set based on the device current location.
2. Second screen width and height for the device are queried using the `WindowManager`.
3. Once the map is centered on the current location then new `LngLat` coordinates are calculated for the adjusted position using `MapController.coordinatesAtScreenPosition(screenWidth/2, screenHeight/4)`.
4. Finally, the map position is set again using the new adjusted coordinates.
While successfully centering the route location marker in the bottom half of the screen this solution has the side effect of causing the map to flicker due to setting the map position twice in rapid succession.
@blair1618 @tallytalwar @karimnaaji is there a way to delay rendering until the final coordinates are calculated? Or is there a better approach we …

Center location maker in bottom half of screen in routing mode

---

app/build.gradle
app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocationImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RouteEngineListener.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/view/VoiceNavigationController.kt
app/src/main/res/values/strings.xml
app/src/test/kotlin/com/mapzen/erasermap/model/MapzenLocationTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/RouteEngineListenerTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/view/TestRouteController.kt

Prevents reroute loops and ensures first verbal instruction is played. Adds "recalculating" verbal alert on reroute.
* Updates LOST to version 1.0.2-SNAPSHOT to include bearing in mock routes.
* Adds minimum displacement for location updates (also reduces map jitter in routing mode).
* Clears TTS queue and plays verbal "recalculating" message on reroute.
* Plays starting instruction as soon as route is set (no longer waits for first location update).
* Initializes TTS engine when `MainActivity` is created to prevent lag when playing first instruction.
Depends on https://github.com/mapzen/on-the-road/pull/52
Closes #213
Closes #111

Improved verbal instructions on route start and reroute

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt
app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt

- Since `tangram-es` API does not provide way to modify feature properties for a `MapData`, we need to rebuild `searchResults` `MapData` everytime active search feature changes.
- By default 1st feature in the search results is marked active.
Fixes #133

Add search feature state property

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt

- Disallow ReveserGeo on an active search
- also fixes an issue with onBackPress when ViewState was ROUTING_PREVIEW. (Should not clear the previous search results)
Fixes #252 
Fixes #251

Disallow reverseGeo on an active search

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt

- Feature Picking:
- If an osm id exists for a picked feature, Pelias Place Search is done to fetch the feature
- Else reverseGeocode is performed at the tapped position
- Feature Picked Pin location is grabbed from the centeroid of the picked feature (which is saved as a property in
tangram). This makes sure feature pick pin is dropped at the correct position
- Small Updates to search pins picking (mainly brevity)
Fixes #254 
**IMPORTANT NOTE: This is dependent on https://github.com/tangrams/tangram-es/pull/489, and should not be merged before `tangram-es` PR is merged.**

Multple feature picking updates

---

app/src/main/kotlin/com/mapzen/erasermap/model/AndroidAppSettings.kt
app/src/main/kotlin/com/mapzen/erasermap/model/AppSettings.kt
app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt
app/src/main/res/values/settings.xml
app/src/main/res/xml/preferences.xml
app/src/test/kotlin/com/mapzen/erasermap/model/AndroidAppSettingsTest.kt
app/src/test/kotlin/com/mapzen/erasermap/model/TestAppSettings.kt

Precise zoom display requested from https://github.com/mapzen/eraser-map/issues/167 with more misc tangram infos printout (current lat/lon, tile cache size, visible tiles, frame time, ...) from https://github.com/tangrams/tangram-es/pull/493

Add debug toggle for misc tangram debug infos

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

Once route preview is initiated clears reverse geo flag to prevent long press and poi tapping. Also fixes in routing mode.
Fixes #271
Fixes #276

Disable reverse geo in route preview mode

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/model/TestMapzenLocation.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

Revises logic in `MainPresenter#onRestoreViewState()` to use `ViewStateManager` to dictate which views should be shown and/or hidden when the activity is recreated. Prevents getting stuck in route preview mode when resuming the app once and for all (I hope).
Tacked on some code cleanup including static import of view states and Kotlin property access syntax.
Fixes #276

Restore view state based on VSM

---

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/res/menu/menu_main.xml
app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt

* Removes search view menu item with action view auto-inflated by options menu.
* Adds `PeliasSearchView` to action bar as fully custom view with layout params.
* Updates custom search icon and clear icon.
* Search view now expands to full width of screen (minus action icons) in portrait and landscape mode.
Fixes #299

Custom search view

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt

- sets the tilt angle to 47.5 (from 60).. since now we have perspective camera we do not need that much tilt
- update the position of the route icon at quater of the screen!
Fixes #323 
It looks like this now:

Update route icon positioning

---

app/src/main/kotlin/com/mapzen/erasermap/util/AxisAlignedBoundingBox.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt

When previewing a route, this will calculate the lon/lat bounding box of the route geometry and move/zoom the map to show the entire route, taking into account the current screen dimensions, with a configurable amount of padding. If no route is found for a search, the preview will now zoom to fit the start and end pins. 
This also adds a utility class for an axis-aligned bounding box - might be useful in other places.

Route preview zooms to fit bounds of the route

---

app/build.gradle
app/src/main/kotlin/com/mapzen/erasermap/view/InitActivity.kt

* Loads production keystore credentials via Gradle properties.
* Adds release signing config.
* Simplifies `BuildConfig` field creation for API keys and build number.
* Hides build number on splash screen in release builds.
* Adds some whitespace between closures to make `build.gradle` more readable.

Adds release build config

---

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt

Allows space for other UI elements above and below
Fixes #386

Constrain route preview to use only half of vertical screen dimension

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteViewController.kt
app/src/test/java/fixtures/long_route.route
app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/view/TestRouteController.kt

When a maneuver is long (over two miles/three kilometers) zoom the map out when in the middle of maneuver. Zoom back in towards end of maneuver.
Closes #339

339 dynamic zoom at transition

---

app/src/main/AndroidManifest.xml

Our MainActivity's launch mode was preventing other activities that it opened from being added to it's task which made it seem like two instances of our app were running.
To reproduce, open settings and then go to the task switcher and see that there are two EraserMap cards in the task switcher.
I tested that notifications still open to the MainActivity when clicked- they do. I noticed that there are some bugs around notifications but the behavior is not due to this change. For example, when we completely kill the app and then click on the notification, it launches the MainActivity but you are not in routing mode. Also, when you cancel a route, the notification still exists until you click "exit navigation" inside the notification.
Let me know if there are other flows I should test aren't …

Change MainActivity's launchMode to singleTask

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt

- Hides setting icon when user is typing and when search results are displayed on map
- Updated text to not clear when search results are shown on map (wasn't able to confirm with Ekta that this is correct behavior so if we want to revert let me know)
Build fails because depends on: https://github.com/pelias/pelias-android-sdk/pull/33
Closes #391

Hide setting action when in search mode

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt

When these aren't set in the same event, it causes the camera to not be set in the correct position

Set mapZoom in same event as mapPostition when centering on location

---

app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/java/com/mapzen/erasermap/CommonModule.java
app/src/main/java/com/mapzen/erasermap/model/SimpleCrypt.java
app/src/main/kotlin/com/mapzen/erasermap/view/InitActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java
app/src/test/java/com/mapzen/erasermap/model/SimpleCryptTest.java
app/src/test/java/com/mapzen/erasermap/shadows/ShadowMapController.java
circle.yml
scripts/encrypter.rb

Runs tests by package in parallel split across 3 nodes (model, view, presenter). Reduces Gradle memory allocation for each node. Uses Circle CI  environment variable test run options.
Also removes `--refresh-dependencies` option to speed up compile time. If you update a library SNAPSHOT version and your build fails due to compile error on Circle CI then try rerunning using "Rebuild without cache" option.
Additional measures to reduce memory consumption include mocking the `Pelias` instance and shadowing additional `MapController` methods to prevent spawn of unwanted background threads during tests.

Parallel tests on Circle CI

---

app/build.gradle
circle.yml

Runs `testDevDebug` using fake API keys. Runs `assembleDevDebug` prior to deployment using real API keys.
Also removes old sliding panel dependency which is no longer used from `build.gradle`.

Fix mint crash

---

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RoutePreviewView.kt
app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt

Also set the time/distance layout to be invisible instead of gone so that spacing is preserved when no route
Closes #425

Disable route preview buttons instead of hiding when no route

---

app/src/main/AndroidManifest.xml
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/service/NotificationService.kt
app/src/main/kotlin/com/mapzen/erasermap/util/NotificationCreator.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt
app/src/main/res/values/strings.xml
app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt

- Fix bug where clicking the cancel route button didnt clear notifications
- Adds hook to kill notifications when app is killed
Creating a stub service that the MainActivity binds to when it creates a notification produced consistent calls to `MainActivity#onDestroy` when the app was killed from the tray. onDestroy calls `NotificationCreator#killNotification` which handles killing the notification and stopping the service.
Closes #280

280 kill notifications

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/controller/MainActivityTest.kt

- Moves searchResults & reverseGeocodeData MapData to MainPresenter so that objects persist on rotation changes
- Exposes MainPresenter's reverseGeo var so that it can be used to properly restore state on rotation changes
- Properly handles rotation changes when reverse geocoded results are shown (centers on map, updates options menu, etc)
Closes #438

438 clear mapdata

---

app/build.gradle
app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/java/com/mapzen/erasermap/EraserMapApplication.java
app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/VoiceNavigationController.kt
app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt

- Make Speakerbox a singleton
- Remove unnecessary mute state handling from RoutePresenter, rely on Speakerbox instead 
- Stop Speakerbox when user cancels routing mode
Depends on: https://github.com/mapzen/speakerbox/pull/8
Closes #408

Speakerbox Rotation Fix

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt

To repro the bug:
- Start routing
- Touch the screen (get the "resume" button to show)
- Back out of the route
- Start a new route
See that:
- Your current location will not be properly centered in the screen until hitting the resume button
Closes #453

Reset location tracking flag when route starts

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

- Updates current location when not in route mode
- We were showing the current location in route preview but then it was hidden when navigating back from route mode. This commit shows the current location marker in route preview on navigating back from the route view to the route preview view
Closes #109

Update location marker always, not just when routing

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/InitActivity.kt
app/src/main/res/layout/activity_main.xml

- Improves perceived launch time on successive launches when application instance hasn't been killed
- Sets `MapView` as a media overlay so that window bg doesn't show on launch (jarring when it does)

Only configure api keys once

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt

- remove redundant call `presenter.routingEnabled = false`
- set `DEFAULT` ViewState when exiting navigation
Closes #349

Fix reversegeo broken after killing navigation from notification

---

app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/java/com/mapzen/erasermap/EraserMapApplication.java
app/src/main/kotlin/com/mapzen/erasermap/util/IntentFactory.kt
app/src/main/kotlin/com/mapzen/erasermap/view/ViewAboutPreference.kt
app/src/main/res/values/settings.xml
app/src/main/res/xml/preferences.xml
app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java
app/src/test/kotlin/com/mapzen/erasermap/mock/MockContext.kt
app/src/test/kotlin/com/mapzen/erasermap/util/MockIntentFactory.kt
app/src/test/kotlin/com/mapzen/erasermap/view/ViewAboutPreferenceTest.kt

This feature is unit tested using the new mockable Android jar framework.
This is a fairly simple test case but requires a decent amount of work on the test harness to get it able to run since this is the first time we are using the mockable Android jar.
I still don't like that that class under test `ViewAboutPreference` has to be mocked in order to successfully run the tests against it. Otherwise `getContext()` always returns null inside the `onClick()` method.
When mocking the class under test its important to call `Mockito.when(classUnderTest.methodUnderTest()).thenCallRealMethod()` to ensure the actual behavior is being tested and you are not just testing the mock.
Closes #495

Adds settings menu "About" link

---

app/build.gradle
app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouteManager.kt
scripts/deploy-master.sh
scripts/deploy.sh

* Updates `build.gradle` to support two new properties: `searchBaseUrl` and `routeBaseUrl`
* Injects base url property values in `BuildConfig.java`
* Uses custom base url values if set when creating `Pelias` and `ValhallaRouter` instance otherwise fall back to default.
* Explicitly enables DNT header for Valhalla requests.
Depends on: https://github.com/mapzen/on-the-road/pull/63
Once merged custom values for search and routing endpoint can be set on Circle CI as needed for production builds. Also allows local builds to point at "dev" server for example simply by updating `gradle.properties`.
cc @baldur 
Fixes #509

Adds ability to inject search and routing base url at build time

---

app/build.gradle
app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/util/DouglasPeuckerReducer.kt
app/src/main/kotlin/com/mapzen/erasermap/util/NotificationCreator.kt
app/src/main/kotlin/com/mapzen/erasermap/view/DirectionListAdapter.kt
app/src/main/kotlin/com/mapzen/erasermap/view/HomeAsUpActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/InitActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java
app/src/test/kotlin/com/mapzen/erasermap/controller/MainActivityTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/view/HomeAsUpActivityTest.kt

Syntax updates:
* Removes redundant `public` modifier from classes and properties where implied
* Adds nullability check `?.` where needed in app code (prevents crashes in production code)
* Adds forced dereference `!!.` where needed in tests (tests should crash if `null` is encountered unexpectedly)
* Uses property access syntax for java setter/getter (ex. `searchView?.setIconified(false)` -> `searchView?.isIconified = false`)
* Adds 'const' modifier to constant values contained in `companion object`s
* Wrap lines at 100 characters
* Cast values in `assertThat(...)` methods to avoid ambiguous method call errors
Depends on https://github.com/mapzen/on-the-road/pull/53
Closes #320

Kotlin 1.0.0-beta-1103 -> 1.0.1

---

app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt

- Persist currentSnapLocation across screen rotations
- Center map if device rotated in route mode
- Some Kotlin 1.0.1 cleanup

Move currentSnapLocation to RoutePresenter

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt

Fixes issue where two API keys were included on each vector tile request (one from the stylesheet and one injected in code at runtime).
* Updates stylesheet submodule to `no-api-key` branch
* Update client data source names to use `mz_*` namespacing
Closes #552

Update style submodule and fix double vector tile API key params

---

app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/java/com/mapzen/erasermap/CommonModule.java
app/src/main/java/com/mapzen/erasermap/EraserMapApplication.java
app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/model/ApiKeys.kt
app/src/main/kotlin/com/mapzen/erasermap/view/InitActivity.kt
app/src/test/kotlin/com/mapzen/erasermap/model/ApiKeysTest.kt

Attempts to prevent loss of API keys when app is put into background and later resumed.
* Makes API keys a member of application class
* Disallows empty strings in API key object constructor
These changes are meant to:
1. Prevent loss of the `ApiKeys` object instance by making it a member of the application class which should persist as long as the process is alive.
2. Fail fast if empty API keys are attempted to be set by throwing an `IllegalArgumentException`.
Fixes #555

Better API key management

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/java/com/mapzen/erasermap/CommonModule.java
app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/model/IntentQuery.kt
app/src/main/kotlin/com/mapzen/erasermap/model/IntentQueryParser.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/InitActivity.kt
app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/model/IntentQueryParserTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

Handle implicit geo and map intents generated by other applications.
* Updates AndroidManifest.xml to receive geo and maps intents
* Log incoming intent and forward to MainActivity
* Perform input validation and pass valid query to parser
* Adds logic to parse query string
* Populate current search term with IntentQueryParser result
* Execute search on incoming query string
* Set map position prior to search based on focus point if available
* Handle implicit intent even if app is already running in background
Closes #545

Handle implicit intents

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

When viewing search results the settings button should remain hidden during device rotation. Posts a delayed runnable to ensure options menu has been created before attempting to hide.
Closes #588

Hide settings button on rotate search results

---

app/src/main/java/com/mapzen/erasermap/EraserMapApplication.java
app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/SearchViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/SearchResultsView.kt
app/src/main/res/values/strings.xml
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

Summary of changes:
* Extract `SearchViewController` interface
* Make `SearchResultsView` compound view implement `SearchViewController` interface
* Makes `searchView` a member of search controller
* Moves `searchView` initialization into `SearchResultsView`
* Fixes auto complete empty view (no recent searches)
* Moves search hint from hardcoded literal to strings.xml
* Fixes full search result list view
* Fixes issue where opening search results list view would cause results to clear on device rotation
* Prevents infinite animation loop by setting view pager position immediately but posting map operations in a delayed runnable (to wait until map is initialized).
* Random Kotlin cleanup
Possible future enhancements:
* Introduce `SearchPresenter` class to maintain search state and handle …

Fix search results animation loop; refactor search

---

app/build.gradle
app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/java/com/mapzen/erasermap/EraserMapApplication.java
app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/model/ApiKeys.kt
app/src/main/kotlin/com/mapzen/erasermap/view/InitActivity.kt
app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java
app/src/test/kotlin/com/mapzen/erasermap/model/ApiKeysTest.kt

- `MainActivity` will initialize the keys when it is created
- Initialization will happen once per application lifecycle

Move ApiKey configuration into init block

---

app/build.gradle
app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

- Moves start/stop of `MapzenLocation` to correspond with start/stop routing mode
- Sets `MapzenMap#isMyLocationEnabled` to be `false` when app exits
- Updates mapzen-android-sdk to 1.0.4-SNAPSHOT which uses a version of LOST that has better handling for multiple `FusedLocationProviderApiImpl` objects

Stop location services when app in bg and not routing

---

app/build.gradle
app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/kotlin/com/mapzen/erasermap/model/AndroidAppSettings.kt
app/src/main/kotlin/com/mapzen/erasermap/model/AppSettings.kt
app/src/main/kotlin/com/mapzen/erasermap/model/Http.java
app/src/main/kotlin/com/mapzen/erasermap/model/RouterFactory.kt
app/src/main/kotlin/com/mapzen/erasermap/model/TileHttpHandler.kt
app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaHttpHandler.java
app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouteManager.kt
app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouterFactory.kt
app/src/main/kotlin/com/mapzen/erasermap/view/DistanceView.kt
app/src/test/kotlin/com/mapzen/erasermap/model/TestAppSettings.kt
app/src/test/kotlin/com/mapzen/erasermap/model/TestRouter.kt
app/src/test/kotlin/com/mapzen/erasermap/model/TestRouterFactory.kt
app/src/test/kotlin/com/mapzen/erasermap/model/ValhallaRouteManagerTest.kt

- Uses sdk's `MapzenRouter` api
- adds DNT header for all routing requests
Depends on: https://github.com/mapzen/android/pull/112

Migrate to MapzenRouter API

---

app/src/main/kotlin/com/mapzen/erasermap/service/NotificationService.kt

According to documentation null intent is valid input to [`Service.onStartCommand(Intent, int, int)`](https://developer.android.com/reference/android/app/Service.html#onStartCommand(android.content.Intent, int, int)). Modify Kotlin to allow nullable parameter.
Closes #620

Allows null value for intent param in notification service

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/model/ConfidenceHandler.kt
app/src/main/kotlin/com/mapzen/erasermap/model/RouteManager.kt
app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouteManager.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/model/TestRouteManager.kt
app/src/test/kotlin/com/mapzen/erasermap/model/ValhallaRouteManagerTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

Adds pseudo-cancellation for route requests by ignoring the response if a request has been canceled.
**Request Cancellation**
A route request is canceled if:
1. The user presses the system back button while the route preview is being generated (slow request, etc.)
2. The user switches routing mode (car, bike, walk) when a request for the previous mode is not yet complete.
**Refactoring**
Moves route fetch logic from `MainActivity` to `MainPresenter`. Ideally all references to `RouteManager` will be removed from `MainActivity` over time but this will require additional refactoring.
**Code Cleanup**
* Remove unused imports.
* Delete public scope modifier when implied for variables and functions.
Closes #626

Cancel route requests on exit route preview

---

app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouteManager.kt

> Building 71% > :app:compileDevDebugKotline: /home/ubuntu/eraser-map/app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouteManager.kt: (105, 5): A 'return' expression required in a function with a block body ('{...}')

Adds `else` condition to `when` statement to fix compile error

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

Explicitly hide the resume button when exiting routing mode. This ensures the correct camera and map position is set when starting a new route.
Fixes #602

Hide resume button on exit routing mode

---

app/src/main/kotlin/com/mapzen/erasermap/view/DistanceView.kt
app/src/main/kotlin/com/mapzen/erasermap/view/InstructionAdapter.kt

Shows distance:
Shows now:
Closes #647

Don't show "now" in directions list, only show in instructions

---

app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt

- Showing all the icons clutters the UI, this PR only shows the first/last station icons
- This also fixes the transit route line not being cleared from the map
Closes #687

limit station icons

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RoutePreviewView.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/route_header.xml
app/src/main/res/layout/view_route_preview.xml

- Fix jumping when switching between modes by setting defined container height (previously it wrapped content)
- Add progressContainer reference
- Move setting of `RoutePreviewView` subview visibility into `RoutePreviewView`
- Fix route preview reverse not being restored on orientation change
Closes #690

Route preview jumping

---

app/src/main/kotlin/com/mapzen/erasermap/view/RoutePreviewView.kt

This PR makes it so that we only update the text views when changing the value of `reverse`. When `reverse` is changed, we issue a route request and upon completion of the request we update `startNavigationButton` 's visibility, taking the values of `reverse` and route mode into account.
Closes #696

Dont update start nav visibility when setting reverse

---

app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt

Replaces `Fragment.getContext().getString()` (API 23) with `Fragment.getString()` (API 11) in `SettingsFragment` debug menu.
Fixes #708

Fix crash on API < 23 devices when debug menu enabled

---

app/build.gradle

Updates to mapzen-android-sdk:1.0.10-SNAPSHOT which uses tangram 0.4.2

mapzen-android-sdk:1.0.10-SNAPSHOT

---

README.md
app/build.gradle
app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/model/ApiKeys.kt
app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java
app/src/test/kotlin/com/mapzen/erasermap/model/ApiKeysTest.kt
app/src/test/kotlin/com/mapzen/erasermap/model/TestRouteManager.kt
circle.yml
scripts/deploy-master.sh
scripts/deploy.sh

- Migrates from 3 keys to 1
- Updates documentation
- Updates deploy scripts
Testing Instructions:
- Update `~/.gradle/gradle.properties` to remove old keys and replace with `apiKey=[API_KEY]`
TODO:
Closes #727

Unified API Key

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt

Two `LostApiClient` objects are connected when the app launches. One is via the Mapzen SDK and another via the `LostClientManager` in EM. We were properly disconnecting the one created in the Mapzen SDK via `mapzenMap?.isMyLocationEnabled = false` but not the one in `LostClientManager`. This PR disconnects EM's `LostApiClient` which removes all of the clients from Lost's underlying client manager and allows the `FusedLocationProviderApi` to disconnect.
Closes #731

Fix location running in bg

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt

This fixes a crash that occurs when the app is backgrounded and then re-opened. We need to reconnect EM's client because it is not connected via map initialization.

Reconnect EM lost client when enabling location

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt

This is already handled in `onPause()`
Fixes #744

No need to disconnect location services in `onDestroy()`

---

app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/model/LocationClientManager.kt
app/src/main/kotlin/com/mapzen/erasermap/model/LostClientManager.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/model/LostClientManagerTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/TestLostClientManager.kt

In an effort to simplify location client management `LostClientManager` no longer actively tracks its connection state. Instead it relies on `LostApiClient.isConnected()` to return proper connection state.
`LostClientManager.getClient()` now always returns the client instance and is no longer nullable. Null checks on the client have been converted to calls to `isConnected()`.

Removes LostClientManager connection state

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/view/TestRouteController.kt

- Adds `onRestoreMapState` method for handling reconfiguring map on orientation changes
- Refactors `routeModeView` configuration into initialization block
Closes #755

Center Map on Orientation Changes

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/SearchResultsView.kt
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

- Updates how we handle restoring the options menu so that we don't try to call methods on it before it has been created
- Fixes bug which prevented options menu buttons from being restored on device rotation when viewing search results
- Fixes bug which didnt restore search results list view on device orientation
- Fixes bug which caused the settings button to show (upon back pressing to search results) when rotating the device while viewing the route preview, route preview directions, route, and route directions screens
Closes #759

Search result restoration

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

This PR prevents the action bar (search bar) from showing when the device is rotated while in route preview mode by hiding it as soon as the action bar is created (previously it wasnt hidden until the route was successfully fetched from the server). It also extracts out some logic for handling what happens when a route is successfully fetched and moves it into the `MainPresenter`/adds test coverage.
Closes #765

Dont show action bar on rotation in route preview mode

---

app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/java/com/mapzen/erasermap/EraserMapApplication.java
app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/model/ConfidenceHandler.kt
app/src/main/kotlin/com/mapzen/erasermap/util/FeatureDisplayHelper.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RoutePreviewView.kt
app/src/main/kotlin/com/mapzen/erasermap/view/SearchResultsAdapter.kt
app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java
app/src/test/kotlin/com/mapzen/erasermap/util/FeatureDisplayHelperTest.kt
app/src/test/kotlin/com/mapzen/erasermap/view/InstructionGrouperTest.kt

- Creates new `FeatureDisplayHelper` class to handle generating display text for a `SimpleFeature`
- Migrates all places in the app where a `SimpleFeature` is displayed to use `FeatureDisplayHelper` 
- Fixes bug where destination text would be blank in route preview view if the feature did not have a name
Closes #769

Always use feature display helper class to display feature name

---

app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/kotlin/com/mapzen/erasermap/model/ConfidenceHandler.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java
app/src/test/kotlin/com/mapzen/erasermap/model/ConfidenceHandlerTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
app/src/test/kotlin/com/mapzen/erasermap/util/FeatureDisplayHelperTest.kt

As a model `ConfidenceHandler` should not know about the presenter. This change removes `MainPresenter` as a dependency of `ConfidenceHandler` and instead uses constructor injection to provide an instance of `ConfidenceHandler` to the presenter when it is created.
This also refactors `MainPresenter` to not track `reverseGeoLngLat` itself but instead store that information in the `ConfidenceHandler` model.
Finally it adds unit tests and docs to `ConfidenceHandler`.

ConfidenceHandler refactor

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

This PR moves logic for exiting navigation, hiding route preview, and centering on features out of the `MainActivity` and into the `MainPresenter` as well as increases test coverage. It replaces large methods with simple calls to UI elements in `MainActivity`. It also adds a fix to reset the tilt when navigation mode is exited. There is a lot more work to do here, this is just a start...

Improve test coverage in MainPresenter

---

build.gradle

Initial testing reveals no build or runtime issues due to the upgrade.

Updates Android Gradle plugin to version 2.2.2

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

This PR stores the search pager position in `MainPresenter` so that it can be used to restore the search results view when either the device is rotated or the user backs out of route preview mode. It also adds tests for this case.
I chose to leave the logic in `MainActivity` to keep the changes in this PR minimal and plan to move this code into the presenter in a separate PR as part of the ongoing test refactoring.
Closes #778

Preserve search pager position on rotation & backing out of route preview

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/view/CompassView.kt
app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

- Sets the compass to be hidden until the map is rotated
- Removes code that made the compass visible when the map was panned (now the compass will only be shown when the map is rotated)
Closes #776

Fix compass always visible

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

Caches the map position and zoom when route preview is generated. When back is pressed for reverse geo requests, the presenter uses these values to restore the map to the previous position and zoom.
Adds two new methods to `MainViewController` for retrieving the map zoom and position.
Closes #779

Restore map position and zoom for reverse geo back press

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

Migrates from `FeaturePickListener` to `LabelPickListener`.
The `LabelPickListener` ensures that coordinates returned are in the center of a label and is better suited for EM's needs.
Closes #775

Single tap consistency

---

app/build.gradle

Upgrades Mapzen Android SDK to version 1.2.1 (includes Tangram 0.4.8)
Resolves search result pin selection via Tangram core fix https://github.com/tangrams/tangram-es/pull/1185
Fixes #800

Upgrade Mapzen Android SDK to version 1.2.1

---

README.md
scripts/deploy.sh

AWS credential environment variables are not available in fork pull requests.
Don't deploy debug APK from fork pull requests. Debug APK should still deploy for Mapzen pull requests.

Fork pull request should not deploy APK to AWS

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/model/event/RouteEvent.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

This PR updates the route preview button `setOnCheckedChangeListener` to consider whether the button has been pressed by the user before updating the route manager and routing
This fixes a bug which, on orientation changes, caused the `setOnCheckedChangeListener` to be invoked which in turn caused the route preview view to show in routing mode
Closes #799

799 route preview orientation

---

app/build.gradle
app/src/main/java/com/mapzen/erasermap/AndroidModule.java
app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/model/ApiKeys.kt
app/src/main/kotlin/com/mapzen/erasermap/model/Http.java
app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocationImpl.kt
app/src/main/kotlin/com/mapzen/erasermap/model/TileHttpHandler.kt
app/src/main/kotlin/com/mapzen/erasermap/model/TmpHttpHandler.java
app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaHttpHandler.java
app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouteManager.kt
app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java
app/src/test/kotlin/com/mapzen/erasermap/model/ApiKeysTest.kt
app/src/test/kotlin/com/mapzen/erasermap/model/LostClientManagerTest.kt
app/src/test/kotlin/com/mapzen/erasermap/model/TestRouter.kt
app/src/test/kotlin/com/mapzen/erasermap/model/ValhallaRouteManagerTest.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt
build.gradle
circle.yml
gradle/wrapper/gradle-wrapper.properties

Upgrades EM to the latest release of the Mapzen Android SDK (1.4.0)
- Upgrades to Kotlin 1.1.2
- Upgrades to Gradle 2.3.3
- Creates temporary `TileHttpHandler` superclass `TmpHttpHandler` to allow for customizing headers in tile requests. This class will be removed and `TileHttpHandler` will be updated to inherit from Tangram class when dependent work is completed (https://github.com/mapzen/eraser-map/issues/821)
Closes #816

Upgrade Mapzen Android SDK

---

app/src/main/kotlin/com/mapzen/erasermap/view/InstructionGroup.kt
app/src/main/kotlin/com/mapzen/erasermap/view/MultiModalDirectionListAdapter.kt
app/src/main/res/values/strings.xml

Added arrival/departure times to the multimodal transit view. Fixes https://github.com/mapzen/eraser-map/issues/699

add transit arrival/departure times

---

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
app/src/main/res/layout/activity_main.xml
app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
app/src/test/kotlin/com/mapzen/erasermap/model/TestMapzenLocation.kt
app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt

- Optimizes how the app handles enabling the location layer. Now it is not enabled when exiting routing mode from the notification if the app is in the background
- Updates the app to unregister the routing location request when routing mode exited from the notification
- Also stops the speaker when exiting routing
- Centers map on current location with default zoom when routing exited
- Updates map overlay mode to "classic" (so that find me button is always at bottom right instead of just when backing out of routing mode)
Underlying Lost issue has been resolve and will be available in a future version of the SDK https://github.com/mapzen/lost/pull/227
Closes #824

Fix Exit Navigation Crash

---

app/build.gradle

Bumps min version to KitKat
Drops support for ~9% of devices running SDKs older than we want to support
Closes #819

Bump Min SDK to 19/4.4/kitkat
