mapzen/eraser-map

app/build.gradle, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/SearchResultsView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/ViewController.kt, build.gradle
Updates gradle plugin, library, and syntax.
=> Kotlin M12

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/res/layout/activity_main.xml
Once https://github.com/tangrams/tangram-es/pull/171 is merged to master, this will enable basic map controls (including during onCreate)
=> Update main activity and layout to use new Tangram classes

app/build.gradle, app/src/test/java/com/mapzen/erasermap/PrivateMapsTestRunner.java, app/src/test/java/com/mapzen/erasermap/view/DistanceViewTest.java, app/src/test/java/com/mapzen/erasermap/view/InstructionListActivityTest.java, app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.java, app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java, app/src/test/java/com/mapzen/erasermap/view/RoutePreviewViewTest.java, app/src/test/java/com/mapzen/erasermap/view/SearchResultsAdapterTest.java, app/src/test/java/com/mapzen/erasermap/view/SearchResultsListActivityTest.java, app/src/test/java/com/mapzen/erasermap/view/SearchResultsViewTest.java
Minor API changes. Simplifies custom shadow config.
=> Robolectric 3.0

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteViewController.kt, app/src/main/res/layout/view_route_mode.xml, app/src/test/java/com/mapzen/erasermap/presenter/MainPresenterTest.java, app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java
* Adds view state enum to main presenter
* Simplifies route mode layout
* Removes unused methods in RouteModeView
=> Maintains sliding panel state on rotation

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
- Fixes orientation changing resulting in multiple reverse geolocated locations.
=> fixes orientation breaking reverse geo

app/build.gradle, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/test/java/com/mapzen/erasermap/dummy/TestHelper.java, app/src/test/java/com/mapzen/erasermap/presenter/MainPresenterTest.java
* Center map on location when route pager is swiped
* Set map tilt in routing mode
* Rotate map based on instruction bearing
=> Set map location, tilt, and rotation in routing mode

app/src/main/java/com/mapzen/erasermap/AndroidModule.java, app/src/main/java/com/mapzen/erasermap/EraserMapApplication.java, app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocation.kt, app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocationImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java, app/src/test/java/com/mapzen/erasermap/presenter/MainPresenterTest.java, app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.java, app/src/test/kotlin/com/mapzen/erasermap/model/MapzenLocationTest.kt, app/src/test/kotlin/com/mapzen/erasermap/model/TestMapzenLocation.kt
* Extracts MapzenLocation model object
* Maintains location updates in background while routing
=> Continue routing while app is in background

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/res/layout/view_route_mode.xml, app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
Temporarily disables route tilt
=> Hide route footer on arrival

app/build.gradle, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/VoiceNavigationController.kt, app/src/test/java/com/mapzen/erasermap/PrivateMapsTestRunner.java, app/src/test/java/com/mapzen/erasermap/shadows/ShadowMapController.java, app/src/test/java/com/mapzen/erasermap/shadows/ShadowMapData.java, app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt, app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt, circle.yml
Note: Includes voice navigation
=> Draw route lines

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/res/values/strings.xml
- Fetches manifest twice if unable to at first.
- Shuts down app if manifest not accesible
=> New Manifest

app/src/main/assets/scene.yaml, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/test/java/com/mapzen/erasermap/shadows/ShadowMapData.java, app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt, app/src/test/kotlin/com/mapzen/erasermap/model/TestRouterFactory.kt
=> Adds location marker to map

app/src/main/assets/scene.yaml, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
=> Search results markers

app/build.gradle, app/src/main/java/com/mapzen/erasermap/AndroidModule.java, app/src/main/java/com/mapzen/erasermap/EraserMapApplication.java, app/src/main/kotlin/com/mapzen/erasermap/model/AndroidAppSettings.kt, app/src/main/kotlin/com/mapzen/erasermap/model/AppSettings.kt, app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocationImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/DirectionListAdapter.kt, app/src/main/kotlin/com/mapzen/erasermap/view/DistanceView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/SettingsActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/VoiceNavigationController.kt, app/src/main/res/layout/direction_list_item.xml, app/src/main/res/values/arrays.xml, app/src/main/res/values/settings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java, app/src/test/kotlin/com/mapzen/erasermap/model/AndroidAppSettingsTest.kt, app/src/test/kotlin/com/mapzen/erasermap/model/MapzenLocationTest.kt, app/src/test/kotlin/com/mapzen/erasermap/model/TestAppSettings.kt, app/src/test/kotlin/com/mapzen/erasermap/model/TestRouterFactory.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/view/SettingsActivityTest.kt
Depends on https://github.com/mapzen/on-the-road/pull/42
=> Routing distance units and settings refactor

app/build.gradle, app/src/main/assets/scene.yaml, app/src/main/kotlin/com/mapzen/erasermap/model/AndroidAppSettings.kt, app/src/main/kotlin/com/mapzen/erasermap/model/AppSettings.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/SearchResultsAdapter.kt, app/src/test/kotlin/com/mapzen/erasermap/model/AndroidAppSettingsTest.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt, build.gradle
Set default distance units based on device Locale.
=> Default distance units

app/build.gradle, app/src/main/assets/scene.yaml, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/SearchResultsAdapter.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt, build.gradle
=> Enable routing tilt

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/test/kotlin/com/mapzen/erasermap/model/TestRouterFactory.kt
Depends on https://github.com/mapzen/on-the-road/pull/44
=> Adds destination name to final routing instruction

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, build.gradle
http://kotlinlang.org/docs/reference/java-interop.html#getters-and-setters
=> Uses Kotlin M13 property access syntax in MainActivity

app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouterFactory.kt
- Fixes bug involving crash if buildconfig is not available.
=> fixes bug involving lack of gradle.properties

app/src/main/java/com/mapzen/erasermap/AndroidModule.java, app/src/main/java/com/mapzen/erasermap/CommonModule.java, app/src/main/java/com/mapzen/erasermap/EraserMapApplication.java, app/src/main/kotlin/com/mapzen/erasermap/model/LocationChangeEvent.kt, app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocation.kt, app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocationImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/model/RouteEvent.kt, app/src/main/kotlin/com/mapzen/erasermap/model/RoutePreviewEvent.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteViewController.kt, app/src/main/res/layout/view_route_mode.xml, app/src/main/res/values/strings.xml, app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java, app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt, app/src/test/kotlin/com/mapzen/erasermap/model/MapzenLocationTest.kt, app/src/test/kotlin/com/mapzen/erasermap/model/TestMapzenLocation.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestRouteController.kt
* Adds logic to show/hide resume button while routing
* Allows user to interact with map in routing mode
* Publishes location updates on the event bus
* Revises `MapzenLocation` API and implementation
* Tracks user location while routing
=> Allow user to interact with map while routing

app/build.gradle, app/src/main/assets/eraser-map.yaml, app/src/main/java/com/mapzen/erasermap/AndroidModule.java, app/src/main/java/com/mapzen/erasermap/CommonModule.java, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RouteEngineListener.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteViewController.kt, app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java, app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt, app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java, app/src/test/kotlin/com/mapzen/erasermap/presenter/RouteEngineListenerTest.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestRouteController.kt
* Use snap location to set icon position in routing mode.
* Add separate MapData layer for routing icon.
* Hide find me icon while in routing mode.
* Hide route icon on exit routing mode.
=> Snap location and rotation

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RouteEngineListener.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteViewController.kt, app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestRouteController.kt
* Allows user to preview upcoming instruction by manually swiping view pager.
* Returns to normal routing mode when "Resume" button is clicked.
=> Manually swipe instruction pager

app/src/main/assets/eraser-map.yaml
transition of hide->show 0sec
- Still better than previous, more work required to make sure old route marker location is not cleared before the new
one gets fetched and added.
=> Update the scene file to make routing icon

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/test/java/com/mapzen/erasermap/shadows/ShadowMapData.java, app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt
Adds `Properties` object to `MapData` method calls.
=> MapData API update

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
This fixes things on eraser-map app side.
However there is regression coming from a recent change to tangram-es core library. I am working on that fix, and should be good by tonight.
=> add data sources and update added data

app/build.gradle, app/src/main/kotlin/com/mapzen/erasermap/model/AndroidAppSettings.kt, app/src/main/kotlin/com/mapzen/erasermap/view/InitActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/SettingsActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt, app/src/main/res/layout/splash_screen.xml, app/src/main/res/values/settings.xml, app/src/main/res/xml/preferences.xml, app/src/test/kotlin/com/mapzen/erasermap/view/SettingsActivityTest.kt, circle.yml
=> Display Circle CI build number on splash screen

app/src/main/java/com/mapzen/erasermap/AndroidModule.java, app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocation.kt, app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocationImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java, app/src/test/java/com/mapzen/erasermap/view/InitActivityTest.kt, app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt, app/src/test/kotlin/com/mapzen/erasermap/model/MapzenLocationTest.kt, app/src/test/kotlin/com/mapzen/erasermap/model/TestMapzenLocation.kt, app/src/test/kotlin/com/mapzen/erasermap/view/SettingsActivityTest.kt
* Update Pelias request params
* Kotlin cleanup
=> Update Pelias Android SDK

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
- Fixes route icon flickering
- NOTE: Currently lacks smooth transition between 2 route icon positions. Marking it as a TODO for further improvements.
Dependency: https://github.com/tangrams/tangram-es/pull/400
=> Updates the client datasource api usage

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt
* Redraws route line after rotation in routing mode
* Removes unused method MainActivity.setBoundingBox()
Closes #86
=> Persist route line on rotation

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
=> Revert "Updates the client datasource api usage"

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
=> Hide search results in routing mode

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
* Default zoom level 16
* Route zoom level 18
Closes #113
=> Update default zoom and route zoom constants

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
=> Increase route tilt from 45 to 60 degrees

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt
=> Redraw route line on reroute

app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
=> Adds easing for map position and rotation in routing mode

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/test/java/com/mapzen/erasermap/dummy/TestHelper.java, app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt
Do not merge yet! 
This is for upcoming changes in tangram-es: https://github.com/tangrams/tangram-es/pull/454
=> Update input callbacks for new API

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt
- add reverseGeocode pin after it has been reverseGeoCoded to a feature.
- Pressing a back button post reverseGeocode should not exit the app now!
- Remove all reverseGeoCode pins when a back button is pressed
- Search results should clear reverseGeocode pins
=> More reverse geo code fixes

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt
=> Select search icons and pois

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
Fixes #249 
~~**IMPORTANT NOTE**: Please wait on https://github.com/tangrams/tangram-es/pull/482 to get merged on tangram-es.~~
=> Use Perspective camera for routing

README.md
Fixes #267
Question here is if we want to surface this to the public or not?
=> Add link to beta builds in README

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
- Zoom by 1 with a duration 1ms
Fixes #250
=> Add DoubleTapResponder

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt
- Dependent on https://github.com/tangrams/tangram-es/pull/491
=> Updated for tangram Property API change

.gitignore, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt
=> More poi tapping improvements

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RoutePreviewView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/TimeView.kt, app/src/main/res/layout/view_route_preview.xml
- Show route preview with no route when no route is found.
- Still draw the start and destination pins!
- Reset Distance and Time to destination
- Refactored some code around drawing routing pins
Future work: Adjust map view to fit the 2 routing pins in screen when no route is found.
Fixes #298
Fixes #287
=> Route Preview Fixes

app/src/main/res/values/styles.xml
Uses styles.xml to update action bar background color.
Fixes #297
=> White search bar

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
In progress
Fixes #260 
Fixes #275 
Fixes #277
=> Fixes resume button functionality.

app/src/main/res/values/colors.xml
"color_accent" is the main green
"color_accent_dark" is for press states of that green (please rename if necessary)
"color_route" is the route line color (nice to have in there for future)
I also edited the grays slightly :)
=> adding some color values

README.md
-Rearranged the order of instructions so that the developer doesn't try building before necessary dependencies are installed
-Updated api key information with link to developer site
Closes #337
=> Update README with more specific developer api key information

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/test/java/com/mapzen/erasermap/shadows/ShadowMapController.java
=> Animate map to next location on swipe through search results

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
=> Force hide resume button on nav start

app/src/main/kotlin/com/mapzen/erasermap/view/InitActivity.kt
Ain't nobody got time for that.
=> Reduce splash screen duration from 3s to 1.2s

app/src/main/res/layout/splash_screen.xml
Adds white background to splash screen layout.
Closes #347
=> Splash screen background

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/view_route_mode.xml, app/src/main/res/layout/view_route_preview.xml, app/src/main/res/layout/view_search_results.xml, app/src/main/res/values/dimens.xml, app/src/main/res/values/strings.xml
Adds TextViews to:
view_route_mode.xml
view_route_preview.xml
activity_main.xml
For activity_main.xml we need to dynamically update the LayoutParams when search results show/hide. I'm updating the values of layout_alignParentBottom and layout_above in code. I could have also implemented by adjusting the layout_marginBottom but it felt less descriptive.
Closes #117
=> Add osm attribution text to map

app/src/main/kotlin/com/mapzen/erasermap/view/InstructionAdapter.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/res/layout/view_route_mode.xml, app/src/test/java/com/mapzen/erasermap/shadows/ShadowMapController.java, app/src/test/java/com/mapzen/erasermap/shadows/ShadowMapData.java, app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java, app/src/test/kotlin/com/mapzen/erasermap/view/InstructionAdapterTest.kt
Update UI at destination so it looks like route is actually complete.
* Display final instruction.
* Hide instruction distance view.
* Hide distance to destination.
* Set route icon location and center map.
* Show top bar with destination name and exit button.
Closes #154
=> Route complete

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainViewController.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestMainController.kt
=> Mute in onClickStartNavigation instead of in startRoutingMode

app/src/main/java/com/mapzen/erasermap/CrashReportService.java
=> Only allow crash reports in debug configuration

app/build.gradle, app/src/main/kotlin/com/mapzen/erasermap/view/VoiceNavigationController.kt, app/src/main/res/values/strings.xml
Build is currently failing bc I have upgraded the snapshot version for on-the-road dependency. I'll rerun the tests after https://github.com/mapzen/on-the-road/pull/54 is merged
Closes #226
=> Add two mile milestone

app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java
=> Use feature name instead of label in destination text view

app/build.gradle, app/src/main/java/com/mapzen/erasermap/AndroidModule.java, app/src/main/java/com/mapzen/erasermap/CommonModule.java, app/src/main/java/com/mapzen/erasermap/SimpleCrypt.java, app/src/main/kotlin/com/mapzen/erasermap/model/ApiKeys.kt, app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouteManager.kt, app/src/main/kotlin/com/mapzen/erasermap/view/InitActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/release-checklist.md, app/src/test/java/com/mapzen/erasermap/SimpleCryptTest.java, app/src/test/kotlin/com/mapzen/erasermap/model/TestRouter.kt, build.gradle, scripts/encrypter.rb, scripts/encrypter.sh
Release builds can now be provisioned with encrypted API keys that will be decoded at runtime.
Closes #362
=> Adds support for encrypted API keys

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RoutePreviewView.kt, app/src/test/java/com/mapzen/erasermap/view/MainActivityTest.kt
- Hides start navigation and view list on route failure. 
Closes #360
=> Hides start navigation and view list on route failure

app/src/main/java/com/mapzen/erasermap/CrashReportService.java
=> Enable crash reports in debug builds

app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt
Depends on: https://github.com/pelias/pelias-android-sdk/pull/34
Closes #411
=> Dont override searchview's imeOptions

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
=> Navigation tilt to 55 degrees

app/src/main/res/layout/view_route_preview.xml
=> Wrap content for routing mode RadioGroup

app/src/main/res/layout/view_route_mode.xml
=> Style resume button

app/src/main/res/color/bg_text_color.xml, app/src/main/res/drawable/bg_button.xml, app/src/main/res/drawable/bg_green_gray_border.xml, app/src/main/res/drawable/bg_white_gray_border.xml, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/route_header.xml, app/src/main/res/layout/view_compass.xml, app/src/main/res/layout/view_mute.xml, app/src/main/res/layout/view_route_mode.xml, app/src/main/res/layout/view_route_preview.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
=> Style route preview btns

circle.yml, scripts/deploy.sh, scripts/perform-release.sh
Adds script to trigger release deployment.
=> Release deployment

app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
=> Update screenY for mapController's nextPositon

app/src/test/kotlin/com/mapzen/erasermap/model/TestRouter.kt
Fix broken unit tests due to library API update.
https://github.com/mapzen/on-the-road/pull/58
=> Implement new methods in test Router

app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocationImpl.kt
Wrapping location logging in DEBUG check
=> Only log current location on debug builds

app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/VoiceNavigationController.kt, app/src/main/res/values/strings.xml
=> Dont announce recalculating on reroute

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt
=> Routing zoom to 17f

app/src/main/kotlin/com/mapzen/erasermap/model/AndroidAppSettings.kt, app/src/main/kotlin/com/mapzen/erasermap/model/AppSettings.kt, app/src/main/kotlin/com/mapzen/erasermap/model/TileHttpHandler.kt, app/src/main/kotlin/com/mapzen/erasermap/view/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/SettingsActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt, app/src/main/res/values/settings.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml, app/src/test/kotlin/com/mapzen/erasermap/model/TestAppSettings.kt
Dependent on: https://github.com/pelias/pelias-android-sdk/pull/36
Closes #388
=> Add toggle for caching searches

app/src/main/kotlin/com/mapzen/erasermap/model/TileHttpHandler.kt
Depends on: https://github.com/tangrams/tangram-es/pull/600
Closes #428
=> Send DNT header in tangram requests

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapzen/erasermap/EraserMapApplication.java, app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/util/NotificationBroadcastReceiver.kt, app/src/main/kotlin/com/mapzen/erasermap/util/NotificationCreator.kt, app/src/main/kotlin/com/mapzen/erasermap/view/InitActivity.kt, app/src/test/java/com/mapzen/erasermap/view/InitActivityTest.kt, app/src/test/java/com/mapzen/erasermap/view/InstructionListActivityTest.java, app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java, app/src/test/kotlin/com/mapzen/erasermap/controller/MainActivityTest.kt, app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt, circle.yml
Update `circle.yml` to run MainActivityTest in its own container.
=> Create controller package for MainActivity

app/src/main/AndroidManifest.xml, app/src/main/res/layout/splash_screen.xml, app/src/main/res/values/styles.xml
Specifies default background color using `android:colorBackground` and `android:windowBackground` in styles.xml.
Closes #457
=> Update app style background color

app/src/main/res/values/settings.xml
=> "Cache Search History" to "Save Search History"

app/build.gradle
Pelias Android SDK 0.7
On the Road 0.8
=> Move pelias SDK and On the Road to release versions

app/build.gradle
Pending library deployment to Maven Central
=> Upgrade LOST to 1.1.0

app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
=> Ignore incoming reroute requests until response is received for existing

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapzen/erasermap/EraserMapApplication.java, app/src/main/kotlin/com/mapzen/erasermap/receiver/MockLocationReceiver.kt, app/src/main/kotlin/com/mapzen/erasermap/view/VoiceNavigationController.kt
=> Dont speak merge instruction on short ramp & add debug location receiver

app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
=> Speak you have arrived

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
=> Clear start & end pins

app/build.gradle, build.gradle, gradle.properties, versioning.gradle
* Moves app version name into `gradle.properties`
* Adds `versioning.gradle` build script extension
* Generates version code automatically at build time
=> Automatically generate app version code

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteViewController.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestRouteController.kt
=> Don't update map on reroute if user interacting with it

app/src/main/kotlin/com/mapzen/erasermap/view/SendFeedbackPreference.kt
Closes https://github.com/mapzen/eraser-map/issues/496
=> Cleaning up the "Send feedback" email

app/src/main/kotlin/com/mapzen/erasermap/presenter/RouteEngineListener.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteViewController.kt, app/src/test/java/com/mapzen/erasermap/view/RouteModeViewTest.java, app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestRouteController.kt
Do not display final instruction or play final verbal instruction until route is fully complete.
=> Route completion refinement

app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
=> Allow map to update if user paging instructions

app/build.gradle, app/src/main/kotlin/com/mapzen/erasermap/view/InstructionAdapter.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
Depends on: https://github.com/mapzen/on-the-road/pull/61
Closes #159
=> Use begin_street_names in pager instruction text before transition

app/src/main/kotlin/com/mapzen/erasermap/view/ReroutingAdapter.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/SearchListViewAdapter.kt, app/src/main/res/layout/pager_item_rerouting.xml, app/src/main/res/values/strings.xml
- Use different adapter to show "Rerouting" in instruction ViewPager
Closes #448
=> Update instruction pager for rerouting

app/src/main/res/drawable/bg_black_gray_border.xml, app/src/main/res/drawable/bg_blue_gray_border.xml, app/src/main/res/drawable/bg_ripple.xml, app/src/main/res/drawable/bg_white_gray_border.xml
Since we are using `<ripple>` for api 21, simply use different colors for pressed states
Closes #515 #516
=> Use colors for press states in layer-list

app/build.gradle, app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
Depends on: https://github.com/pelias/pelias-android-sdk/pull/39
Closes #470
=> Disable keyboard auto show when viewing search results list

app/build.gradle
Depends on https://github.com/tangrams/tangram-es/pull/614
Closes #403
=> Update Tangram dependency to release v0.1

app/src/main/res/layout/view_route_mode.xml
=> Make footer view consume touches so map doesnt move when footer touched

app/src/main/res/layout/pager_item_search_results.xml
=> Fix padding on search results view

app/src/main/kotlin/com/mapzen/erasermap/view/DirectionItemClickListener.kt, app/src/main/kotlin/com/mapzen/erasermap/view/DirectionListAdapter.kt, app/src/main/kotlin/com/mapzen/erasermap/view/DirectionListView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/InstructionListActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/test/java/com/mapzen/erasermap/view/InstructionListActivityTest.java
- Migrate DirectionListAdapter to use ViewHolder pattern
- More Kotlin 1.0 syntax fixes
Closes #519
=> Go to direction when tapping list item

app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt
=> Hide resume btn when viewing directions

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
Required for this week's v0.9 tile release (else city labels will disappear).
Also fixes roads (missing roads geoms, missing labels) and a few other things.
=> fixes #537 for bubble-wrap.yaml adoption

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
=> Fix place search OSM ID

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
=> 550 search results editable listview

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
=> Clear reverseGeoLngLat when search results come back

app/build.gradle, app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt, app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
Requires additional nullability checks around feature list method params.
=> Upgrade Kotlin to version 1.0.2

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/model/AppSettings.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
=> Migrate to MapzenMap api

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
=> Don't clear and redraw route line on rotation

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
=> Dont show current location when routing

.gitmodules, README.md, circle.yml
No longer needed as we are loading the stylesheet from the SDK
=> Rm bubble-wrap submodule

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
=> Remove use of place query, always make reverse call

app/build.gradle, app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
- Update to mapzen-android-sdk 1.0.3
- Remove unneccesary clear pins in onDestroy
- Fix bug that prevented find me button from being reshown after exiting navigation
Closes #571
=> Dont clear pins on rotation

app/build.gradle
- Adds support for multiple listeners in LOST
=> Update to mapzen 1.0.4-SNAPSHOT

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt
https://github.com/mapzen/android/pull/107
Closes #601
=> Let SDK handle find me button behavior

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
Wait until map is loaded to init rotate listener.
Closes #608
=> Fix compass rotation

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
Adust calculated margins for find me button and attribution. Uses SDK dimens values.
Depends on https://github.com/mapzen/android/pull/108
Closes #594
=> Update find me button padding

app/src/main/java/com/mapzen/erasermap/AndroidModule.java, app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt, app/src/main/kotlin/com/mapzen/erasermap/model/LocationConverter.kt, app/src/main/kotlin/com/mapzen/erasermap/model/RouteManager.kt, app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouteManager.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RouteEngineListener.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/RoutePresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteViewController.kt, app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java, app/src/test/java/com/mapzen/erasermap/dummy/TestHelper.java, app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt, app/src/test/kotlin/com/mapzen/erasermap/model/TestAppSettings.kt, app/src/test/kotlin/com/mapzen/erasermap/model/TestRouteManager.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/RoutePresenterTest.kt, app/src/test/kotlin/com/mapzen/erasermap/view/TestRouteController.kt
Depends on:
https://github.com/mapzen/on-the-road/pull/69
https://github.com/mapzen/android/pull/109
=> Replace android location objects for mapzen location objects

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
-Zooms map in on current location on first launch
=> Invoke find me when permissions granted

app/src/main/kotlin/com/mapzen/erasermap/view/SearchResultsAdapter.kt
=> Show dropped pin as title if feature doesnt have name

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
=> Deactivate find me tacking upon entering search results or route preview

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouteManager.kt, app/src/main/res/drawable/ic_transit_checked.xml, app/src/main/res/drawable/ic_transit_normal.xml, app/src/main/res/drawable/radio_button_transit.xml, app/src/main/res/layout/view_route_preview.xml
=> Add mulitmodal support

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt
=> Reset camera on exit navigation

app/src/main/kotlin/com/mapzen/erasermap/model/AndroidAppSettings.kt, app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/debug_preferences.xml
Depends on: https://github.com/mapzen/android/pull/133
Closes #635
=> Display tangram version in debug settings

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/DirectionListAdapter.kt
=> 649 distance errors

app/src/main/res/layout/view_route_preview.xml, app/src/main/res/values/strings.xml
* Updates route preview button text from "View List" to "View Directions".
* Makes list and start nav buttons have same width to accommodate longer text.
* Adds `maxLines`, `singleLine`, and `ellipsize` attributes to prevent text wrap on smaller screens.
Closes #641
=> Update "View Directions" button

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt
=> Hide start nav button on rotation

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RoutePreviewView.kt, app/src/main/res/layout/view_route_preview.xml, app/src/main/res/values/strings.xml
- Load `RoutePreviewView`'s views using `lazy`
- Remove toast when no route found
Closes #671
=> Hide start nav and view directions btns when no route found

app/src/main/res/drawable/dashed_line.xml, app/src/main/res/layout/icon_title_row.xml, app/src/main/res/layout/instruction_row.xml, app/src/main/res/layout/pedestrian_direction_row.xml, app/src/main/res/layout/transit_direction_row.xml, app/src/main/res/layout/transit_station_row.xml, app/src/main/res/layout/view_route_preview.xml, app/src/main/res/values/dimens.xml
- walking instructions color to `color_primary_dark`
- thicker transit and pedestrian lines
- updated color of pedestrian line
- remove background transparency
- use `dimen` constants
- use new pedestrian icon
Closes #670 
Closes #667 
Closes #666 
Closes #665
=> Polish multimodal route preview UI

app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocationImpl.kt
=> Return map's position for autocomplete query

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
- Pass poiTapPoint(1) for screenY, not poiTapPoint(0)
- Replace use of `android.graphics.PointF` in `TestMainController` with `com.mapzen.tangram.LngLat`
- Reformat `MainPresenterImpl`
Closes #672
=> Fix incorrect results showing for reverse geocode

app/build.gradle, app/src/main/java/com/mapzen/erasermap/AndroidModule.java, app/src/main/java/com/mapzen/erasermap/EraserMapApplication.java, app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/model/AndroidAppSettings.kt, app/src/main/kotlin/com/mapzen/erasermap/model/AppSettings.kt, app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocation.kt, app/src/main/kotlin/com/mapzen/erasermap/model/MapzenLocationImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/model/RouterFactory.kt, app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaHttpHandler.java, app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouteManager.kt, app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouterFactory.kt, app/src/main/kotlin/com/mapzen/erasermap/view/DistanceView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/RouteModeView.kt, app/src/main/kotlin/com/mapzen/erasermap/view/SearchResultsView.kt, app/src/main/res/layout/activity_main.xml, app/src/test/java/com/mapzen/erasermap/TestAndroidModule.java, app/src/test/kotlin/com/mapzen/erasermap/model/TestAppSettings.kt, app/src/test/kotlin/com/mapzen/erasermap/model/TestMapzenLocation.kt, app/src/test/kotlin/com/mapzen/erasermap/model/TestRouter.kt, app/src/test/kotlin/com/mapzen/erasermap/model/TestRouterFactory.kt
Closes #709, Closes #705, Closes #707
=> Migrate to Android SDK 1.0.8, Tangram 0.4.1

app/build.gradle, app/src/main/AndroidManifest.xml
- Upgrade SDK to include Lost commit https://github.com/mapzen/lost/commit/aae777522ff0c275a060d530c2932737799f39e3
- Remove unnecessary bluetooth permission
Closes #730
=> Rm BT Permission

app/build.gradle
Upgrades mapzen android sdk to version 1.2.0-SNAPSHOT for testing
=> Upgrades mapzen android sdk to version 1.2.0-SNAPSHOT for testing

app/src/main/kotlin/com/mapzen/erasermap/view/SearchResultsView.kt
- Fixes crash resulting from autocomplete list not being initialized
- Removes redundant adapter initialization call
Closes #757
=> Search list crash

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
=> Reset tilt when find me clicked

app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenter.kt, app/src/main/kotlin/com/mapzen/erasermap/presenter/MainPresenterImpl.kt, app/src/main/kotlin/com/mapzen/erasermap/view/SearchResultsView.kt, app/src/main/res/values/strings.xml, app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt, app/src/test/kotlin/com/mapzen/erasermap/presenter/MainPresenterTest.kt
* Toast error message for empty search results
* Focus search view and set cursor position
* Misc code cleanup and remove unused imports
Fixes #781
=> Handle empty search results

app/build.gradle, circle.yml
Resolves #793 
Updates SDK, Tools, and Support Libraries to API 25
/cc @sarahlensing @ecgreb
=> #793 - Updating SDK, Tools, and Support Libraries to API 25

app/build.gradle, app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/controller/MainViewController.kt, app/src/main/kotlin/com/mapzen/erasermap/model/AndroidAppSettings.kt, app/src/main/kotlin/com/mapzen/erasermap/model/AppSettings.kt, app/src/main/kotlin/com/mapzen/erasermap/view/SettingsFragment.kt, app/src/main/res/values/arrays.xml, app/src/main/res/values/settings.xml, app/src/main/res/xml/preferences.xml, app/src/test/kotlin/com/mapzen/erasermap/controller/TestMainController.kt, app/src/test/kotlin/com/mapzen/erasermap/model/TestAppSettings.kt, build.gradle, circle.yml
Implement House Styles Switcher from #700.  Supports BubbleWrap, Refill, Walkabout, Cinnabar, and Zinc.
Add Styles Switcher UI for Preferences API inside existing Settings screen.
/cc @ecgreb @nvkelso @sarahlensing
=> Add House Styles Switcher

app/build.gradle, app/src/main/kotlin/com/mapzen/erasermap/controller/MainActivity.kt, app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaHttpHandler.java, app/src/main/kotlin/com/mapzen/erasermap/model/ValhallaRouteManager.kt
Upgrades Mapzen SDK to version 1.3.0-SNAPSHOT (OkHttp3/Retrofit2)
Upgrade SDK, OkHttp, and Retrofit dependencies
=> Upgrades Mapzen SDK to version 1.3.0-SNAPSHOT (OkHttp3/Retrofit2)
